# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/keepeuh/code/test-cig

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/keepeuh/code/test-cig

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/keepeuh/code/test-cig/CMakeFiles /home/keepeuh/code/test-cig//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/keepeuh/code/test-cig/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Cigarettes

# Build rule for target.
Cigarettes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Cigarettes
.PHONY : Cigarettes

# fast build rule for target.
Cigarettes/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/build
.PHONY : Cigarettes/fast

#=============================================================================
# Target rules for targets named Cigarettes

# Build rule for target.
Cigarettes: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Cigarettes
.PHONY : Cigarettes

# fast build rule for target.
Cigarettes/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/build
.PHONY : Cigarettes/fast

src/CommandHandler.o: src/CommandHandler.cpp.o
.PHONY : src/CommandHandler.o

# target to build an object file
src/CommandHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/CommandHandler.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/CommandHandler.cpp.o
.PHONY : src/CommandHandler.cpp.o

src/CommandHandler.i: src/CommandHandler.cpp.i
.PHONY : src/CommandHandler.i

# target to preprocess a source file
src/CommandHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/CommandHandler.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/CommandHandler.cpp.i
.PHONY : src/CommandHandler.cpp.i

src/CommandHandler.s: src/CommandHandler.cpp.s
.PHONY : src/CommandHandler.s

# target to generate assembly for a file
src/CommandHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/CommandHandler.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/CommandHandler.cpp.s
.PHONY : src/CommandHandler.cpp.s

src/ProtocolHandler.o: src/ProtocolHandler.cpp.o
.PHONY : src/ProtocolHandler.o

# target to build an object file
src/ProtocolHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/ProtocolHandler.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/ProtocolHandler.cpp.o
.PHONY : src/ProtocolHandler.cpp.o

src/ProtocolHandler.i: src/ProtocolHandler.cpp.i
.PHONY : src/ProtocolHandler.i

# target to preprocess a source file
src/ProtocolHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/ProtocolHandler.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/ProtocolHandler.cpp.i
.PHONY : src/ProtocolHandler.cpp.i

src/ProtocolHandler.s: src/ProtocolHandler.cpp.s
.PHONY : src/ProtocolHandler.s

# target to generate assembly for a file
src/ProtocolHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/ProtocolHandler.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/ProtocolHandler.cpp.s
.PHONY : src/ProtocolHandler.cpp.s

src/api/library.o: src/api/library.cpp.o
.PHONY : src/api/library.o

# target to build an object file
src/api/library.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/api/library.cpp.o
.PHONY : src/api/library.cpp.o

src/api/library.i: src/api/library.cpp.i
.PHONY : src/api/library.i

# target to preprocess a source file
src/api/library.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/api/library.cpp.i
.PHONY : src/api/library.cpp.i

src/api/library.s: src/api/library.cpp.s
.PHONY : src/api/library.s

# target to generate assembly for a file
src/api/library.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/api/library.cpp.s
.PHONY : src/api/library.cpp.s

src/libConfig.o: src/libConfig.cpp.o
.PHONY : src/libConfig.o

# target to build an object file
src/libConfig.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libConfig.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libConfig.cpp.o
.PHONY : src/libConfig.cpp.o

src/libConfig.i: src/libConfig.cpp.i
.PHONY : src/libConfig.i

# target to preprocess a source file
src/libConfig.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libConfig.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libConfig.cpp.i
.PHONY : src/libConfig.cpp.i

src/libConfig.s: src/libConfig.cpp.s
.PHONY : src/libConfig.s

# target to generate assembly for a file
src/libConfig.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libConfig.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libConfig.cpp.s
.PHONY : src/libConfig.cpp.s

src/libCrypto.o: src/libCrypto.cpp.o
.PHONY : src/libCrypto.o

# target to build an object file
src/libCrypto.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libCrypto.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libCrypto.cpp.o
.PHONY : src/libCrypto.cpp.o

src/libCrypto.i: src/libCrypto.cpp.i
.PHONY : src/libCrypto.i

# target to preprocess a source file
src/libCrypto.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libCrypto.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libCrypto.cpp.i
.PHONY : src/libCrypto.cpp.i

src/libCrypto.s: src/libCrypto.cpp.s
.PHONY : src/libCrypto.s

# target to generate assembly for a file
src/libCrypto.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libCrypto.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libCrypto.cpp.s
.PHONY : src/libCrypto.cpp.s

src/libCryptoSession.o: src/libCryptoSession.cpp.o
.PHONY : src/libCryptoSession.o

# target to build an object file
src/libCryptoSession.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libCryptoSession.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libCryptoSession.cpp.o
.PHONY : src/libCryptoSession.cpp.o

src/libCryptoSession.i: src/libCryptoSession.cpp.i
.PHONY : src/libCryptoSession.i

# target to preprocess a source file
src/libCryptoSession.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libCryptoSession.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libCryptoSession.cpp.i
.PHONY : src/libCryptoSession.cpp.i

src/libCryptoSession.s: src/libCryptoSession.cpp.s
.PHONY : src/libCryptoSession.s

# target to generate assembly for a file
src/libCryptoSession.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libCryptoSession.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libCryptoSession.cpp.s
.PHONY : src/libCryptoSession.cpp.s

src/libHost.o: src/libHost.cpp.o
.PHONY : src/libHost.o

# target to build an object file
src/libHost.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libHost.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libHost.cpp.o
.PHONY : src/libHost.cpp.o

src/libHost.i: src/libHost.cpp.i
.PHONY : src/libHost.i

# target to preprocess a source file
src/libHost.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libHost.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libHost.cpp.i
.PHONY : src/libHost.cpp.i

src/libHost.s: src/libHost.cpp.s
.PHONY : src/libHost.s

# target to generate assembly for a file
src/libHost.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libHost.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libHost.cpp.s
.PHONY : src/libHost.cpp.s

src/libNetwork.o: src/libNetwork.cpp.o
.PHONY : src/libNetwork.o

# target to build an object file
src/libNetwork.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libNetwork.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libNetwork.cpp.o
.PHONY : src/libNetwork.cpp.o

src/libNetwork.i: src/libNetwork.cpp.i
.PHONY : src/libNetwork.i

# target to preprocess a source file
src/libNetwork.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libNetwork.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libNetwork.cpp.i
.PHONY : src/libNetwork.cpp.i

src/libNetwork.s: src/libNetwork.cpp.s
.PHONY : src/libNetwork.s

# target to generate assembly for a file
src/libNetwork.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libNetwork.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/libNetwork.cpp.s
.PHONY : src/libNetwork.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/torManager.o: src/torManager.cpp.o
.PHONY : src/torManager.o

# target to build an object file
src/torManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/torManager.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/torManager.cpp.o
.PHONY : src/torManager.cpp.o

src/torManager.i: src/torManager.cpp.i
.PHONY : src/torManager.i

# target to preprocess a source file
src/torManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/torManager.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/torManager.cpp.i
.PHONY : src/torManager.cpp.i

src/torManager.s: src/torManager.cpp.s
.PHONY : src/torManager.s

# target to generate assembly for a file
src/torManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/torManager.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Cigarettes.dir/build.make CMakeFiles/Cigarettes.dir/src/torManager.cpp.s
.PHONY : src/torManager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Cigarettes"
	@echo "... Cigarettes"
	@echo "... src/CommandHandler.o"
	@echo "... src/CommandHandler.i"
	@echo "... src/CommandHandler.s"
	@echo "... src/ProtocolHandler.o"
	@echo "... src/ProtocolHandler.i"
	@echo "... src/ProtocolHandler.s"
	@echo "... src/api/library.o"
	@echo "... src/api/library.i"
	@echo "... src/api/library.s"
	@echo "... src/libConfig.o"
	@echo "... src/libConfig.i"
	@echo "... src/libConfig.s"
	@echo "... src/libCrypto.o"
	@echo "... src/libCrypto.i"
	@echo "... src/libCrypto.s"
	@echo "... src/libCryptoSession.o"
	@echo "... src/libCryptoSession.i"
	@echo "... src/libCryptoSession.s"
	@echo "... src/libHost.o"
	@echo "... src/libHost.i"
	@echo "... src/libHost.s"
	@echo "... src/libNetwork.o"
	@echo "... src/libNetwork.i"
	@echo "... src/libNetwork.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/torManager.o"
	@echo "... src/torManager.i"
	@echo "... src/torManager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

